import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-slate-100'>
          <h1 className='pt-4 text-4xl text-center'>my-next-crud</h1>
          <nav className='flex justify-end'>
            <Link href='/' className='hover:text-slate-500'>Home</Link>
            <Link href='/add' className='px-4 hover:text-slate-500'>Add</Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  )
}
